### ISSUE TITLE
confused on uuid_extractor_output.json format

### ISSUE THREAD

**Issue by nutc4k3** [projectbtle/uuid-function-mapper#1]
Hi!

First of all thanks for this tool!! 
For the question, I am a bit confused about the format of uuid_extractor_output.json, what do you mean by "methods", the actual methods called by the app or some other GATT protocol hierarchy? 

Thanks in advance! :)

**Comment by projectbtle** [comment]
Hi, apologies for the delay in responding.

"method" refers to the Android Java methods in smali format.
e.g., `"Lcom/example/myble/SomeClass;->someMethod()V"`

Hope this helps!
